### ISSUE TITLE
how-to-npm isout-of-date :(

### ISSUE THREAD

**Issue by ashleygwilliams** [sindresorhus/awesome-npm#2]
i'm working on building maintenance of it into my schedule, but it's p much unmaintained rn and has some pretty brutal bugs on windows. you might consider removing, or adding a warning.

**Comment by sindresorhus** [comment]
Alright, removing for now. Let me know when it's usable again ;)

**Comment by sindresorhus** [comment]
You should probably add a note about it in its readme.
