### ISSUE TITLE
Add [npm-check-updates] to npm packages

### ISSUE THREAD

**Issue by yordis** [sindresorhus/awesome-npm#3]
This is very helpful for check the packages and update it.

Link: https://www.npmjs.com/package/npm-check-updates

**Comment by stevemao** [comment]
Yep, I think it's probably a better tool than david. Although they have slightly different scopes.

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/awesome-npm/pull/7.

**Comment by yordis** [comment]
I didn't know about that one. hah Awesome Kappa
