### ISSUE TITLE
Where to link to external tips / guide?

### ISSUE THREAD

**Issue by jbmoelker** [sindresorhus/awesome-npm#40]
I'd like to suggest the following resource:

[npm Style Guide](https://github.com/voorhoede/npm-style-guide#readme) - An opinionated collection of best practices for teams by [De Voorhoede](https://twitter.com/devoorhoede).

However, I'm not sure which category / section it should be put in. Normally I'd say _tips_, but that section consists of inline content rather than links to other resources.

So my question is, where should I place the link to this resource?

**Comment by sindresorhus** [comment]
I could see the usefulness of something like this, but this one is a bit too opinionated and has a lot of incorrect statements*. I'd rather link to something more generic or include more tips inline in the Tips section.

## 

*⬇️ 

https://github.com/voorhoede/npm-style-guide#use-save-exact-option

> While this is a good idea as is, this makes it possible for different developers having different versions of the same package and making it harder to debug if there is inconsistency. Defining the save-exact option prevents this.

Incorrect... Pinning your dependencies only works on the top-level. Imagine you pin top-level dependency `a` which depends on `b`. If `b` does a buggy patch release you'll still get it, as `a` has not pinned its dependencies. The only way this can work is if the whole dependency tree have their dependencies pinned, which is totally unfeasible. The correct solution is to use `^` and use shrinkwrap or committing dependencies for safety.

**Comment by jbmoelker** [comment]
Fair enough. I understand the feedback. Shrinkwrap comes with its own issues, so that's why we're taking this approach. You are right it doesn't solve everything.
