### ISSUE TITLE
Add better npm completion

### ISSUE THREAD

**Issue by lukechilds** [sindresorhus/awesome-npm#42]
I have written some better npm completion for zsh users: [`zsh-better-npm-completion`](https://github.com/lukechilds/zsh-better-npm-completion). Is this something you'd be interested in featuring here?

**Comment by sindresorhus** [comment]
Definitely. Can you do a pull request?

**Comment by lukechilds** [comment]
Sweet!

Yeah, I wasn't too sure where to put it? A new CLI sub section under Tools maybe?

**Comment by sindresorhus** [comment]
Sure
