### ISSUE TITLE
Mention lifecycle scripts

### ISSUE THREAD

**Issue by nexdrew** [sindresorhus/awesome-npm#6]
In your "Run scripts" section, it might be worth mentioning that you can tell npm to automatically run scripts before or after certain lifecycle events of your package, e.g. `pretest`, `prepublish` or `postinstall`:

``` json
{
  "name": "the-awesomest",
  "scripts": {
    "pretest": "xo",
    "test": "npm run prepublish && nyc ava",
    "prepublish": "babel lib --out-dir=dist",
    "postinstall": "echo 'Thanks for installing The Awesomest'"
  },
  "devDependencies": {
    "ava": "^0.9.1",
    "babel": "^6.3.26",
    "nyc": "^5.0.1",
    "xo": "^0.12.1"
  },
  "xo": {
    "esnext": true
  }
}
```

A link to https://docs.npmjs.com/misc/scripts might be helpful too.

**Comment by sindresorhus** [comment]
:+1:
