### ISSUE TITLE
Trick for avoiding relative requires?

### ISSUE THREAD

**Issue by rreusser** [sindresorhus/awesome-npm#9]
Is there a good approach for avoiding relative requires, e.g. `require '../../../../../foo/bar.js'`? Between symlinks, just dealing with it, a [linklocal](https://www.npmjs.com/package/linklocal) trick I'm using right now, and various other ad-hoc solutions, it's not clear to me whether there's a magic bullet.

If there's a good, concise answer to this, I think it would be a great addition to a list of things that make npm awesome!

**Comment by sindresorhus** [comment]
I generally think you should consider splitting up your code into multiple packages if you have that much nesting, but I'll keep the issue open for feedback.

**Comment by rreusser** [comment]
Thanks. For a hopefully-low-complexity-node module I totally agree. Our current use-case is a react-native project. We have `app/views` and `app/components`, and if you add one subdirectory, that's really all it takes to bring on a mess of relative requires.

(**_Edit: realizes that yes, the original example was indeed rather excessive**_)

**Comment by rreusser** [comment]
I think it's a common challenge, but I'm totally content to close if the answer is that it's an anti-pattern to be avoided in the first place.

**Comment by sindresorhus** [comment]
@rreusser I'll keep it open. I was just talking in general. I'm interested in seeing some suggestion for this too.

**Comment by rreusser** [comment]
The best I have:
1. Add `"app": "file:./app"` to `package.json`
2. `$ cd app && npm init -y`

Then the installation instructions are just:
1. `$ npm i -g linklocal`
2. `$ linklocal && npm i`

and `require('app/...')` works throughout the app. The result is nothing more than a symlink, but it's significantly easier to communicate to collaborators than manual symlinks.

**Comment by mastilver** [comment]
If you are using `babel`, you should try https://github.com/michaelzoidl/babel-root-import
I only find myself using it inside my test files

**Comment by sindresorhus** [comment]
Babel plugins:
- https://github.com/schiehll/babel-plugin-dot-dot-slash
- https://github.com/michaelzoidl/babel-root-import
- https://github.com/per2plex/babel-project-relative-import
- https://github.com/bh5-js/babel-plugin-module-map

**Comment by alejandronanez** [comment]
What about adding an npm script like: 
`"start": "NODE_PATH=./app/ && node ./app/app.js"`
Then you can do inside your app something like: `const foo = require('foo/baz/baz/foo');` from anywhere inside `app/`
